### ISSUE TITLE
2D and 3D points

### ISSUE THREAD

**Issue by 1995parham** [aiotrc/GoRunner#16]
Codecs can return 2D and 3D points instead of an object if they want. these points represent locations.

**Comment by 1995parham** [comment]
@sajjadrahnama7 What do you think? I can start implementation of this feature by assuming that these tuples represent the location.

**Comment by BahadorAUT** [comment]
The "windowing" mechanism for one dimensional data has more priority than this type of data.

**Comment by sajjadrahnama7** [comment]
I agree.
